#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Manually set a 256color TERM variable for vte-based terminals which can't be configured to set it themself
if [[ "$COLORTERM" =~ "(gnome|xfce4)-terminal" ]]; then
    export TERM="xterm-256color"
fi

# If the terminal support 256 colours, then redefine the colorspace for base16 theme
if [[ "$(tput colors)" -eq 256 ]]; then
    source "$HOME/src/base16-builder/output/shell/base16-default.dark.sh"
fi
