#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Manually set a 256color TERM variable for vte-based terminals which can't be configured to set it themself
if [[ "$COLORTERM" =~ "(gnome|xfce4)-terminal" ]]; then
    export TERM="xterm-256color"
fi

# If we're not using PuTTY, remap 256 colorspace
if [[ ! "$TERM" =~ "putty" ]]; then
    source $HOME/src/base16-builder/output/shell/base16-default.dark.sh
fi
